[package]
name = "styx_z"
version = "0.1.0"
authors = ["Dennis Waldherr <bytekeeper@mailbox.org>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
#rsbwapi = { git = "https://github.com/Bytekeeper/rsbwapi.git" }
rsbwapi = { path = "../rsbwapi" }
memchr = "2.2.2"
derive_more = "0.99"
