[build]
target="i686-pc-windows-msvc"
#target="i686-pc-windows-gnu"
# target="x86_64-pc-windows-gnu"

[target.i686-pc-windows-msvc]
linker = "lld"
rustflags = [
  "-Lnative=/tmp/.xwin/crt/lib/x86",
  "-Lnative=/tmp/.xwin/sdk/lib/um/x86",
  "-Lnative=/tmp/.xwin/sdk/lib/ucrt/x86"
]
