name: Linux cross compile GNU toolchain

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Setup system
      run: |
        apt install llvm-dev libclang-dev clang
    - name: Install windows target and xwin
      run: |
        cargo install xwin
        rustup target add i686-pc-windows-msvc
        cargo install cross
        xwin --accept-license splat --output /tmp/.xwin
    - uses: actions/checkout@v3
    - name: Build
      run: cross build --verbose --release
    - name: Run tests
      run: cargo test --verbose
