name: Linux cross compile GNU toolchain

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Install windows target
      run: |
        cargo install cross
        rustup target add i686-pc-windows-gnu
    - uses: actions/checkout@v3
    - name: Build
      run: cross build --verbose --release
    - name: Run tests
      run: cargo test --verbose
