name: Windows Build

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always
  CARGO_BUILD_RUSTFLAGS: -C target-feature=+crt-static -C link-arg=/SUBSYSTEM:CONSOLE,5.01

jobs:
  build:

    runs-on: windows-latest

    steps:
    - name: Install windows target
      run: |
        rustup update
        rustup target add i686-pc-windows-msvc
    - uses: actions/checkout@v3
    - name: Build
      run: cargo build --verbose --target i686-pc-windows-msvc --release
    - name: Run tests
      run: cargo test --verbose --target i686-pc-windows-msvc
    - run: |
        copy target\i686-pc-windows-msvc\release\styx_z.exe .
        copy dist\run_proxy.bat .
    - uses: actions/upload-artifact@v3
      with:
        name: aiide
        path: |
          styx_z.exe
          LICENSE.md
          Cargo.toml
          Cargo.lock
          src
          run_proxy.bat
          README.md
    - uses: actions/upload-artifact@v3
      with:
        name: sscait
        path: |
          styx_z.exe
          run_proxy.bat
          BWAPI.dll
