name: Windows Build

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: windows-latest

    steps:
    - name: Install windows target
      run: rustup target add i686-pc-windows-msvc
    - uses: actions/checkout@v3
    - name: Build
      run: cargo build --verbose --target i686-pc-winows-msvc
    - name: Run tests
      run: cargo test --verbose --target i686-pc-winows-msvc
