name: Windows Build

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: windows-latest

    steps:
    - name: Install windows target
      run: rustup target add i686-pc-windows-msvc
    - uses: actions/checkout@v3
    - name: Build
      run: cargo build --verbose --target i686-pc-windows-msvc --release
    - uses: actions/upload-artifact@v3
      with:
        name: styxz.zip
        path: target/styxz.zip
    - name: Run tests
      run: cargo test --verbose --target i686-pc-windows-msvc
    - run: 7z a target/styxz.zip target/i686-pc-windows-msvc/release/styx_z.exe dist/run_proxy.bat Cargo.toml Cargo.lock LICENSE.md
    - run: 7z a target/styxz.zip -r src
    - run: 7z rn target/styxz.zip dist/run_proxy.bat run_proxy.bat src sources/src Cargo.toml sources/Cargo.toml Cargo.lock sources/Cargo.lock target/i686-pc-windows-msvc/release/styx_z.exe styx_z.exe
